language: c

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

cache:
    - apt

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install php5 php5-dev
    - sudo apt-get install libgtest-dev

before_script:
    - make all PHPDIR=/usr/local/


script:
    - tests/phptrace_unittest

